# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b9e945845388918d32679770b5e19152b4562225ca56f364b747aada62ab8cd33d00456935ba06e480a7fafd38a1973f3c9304372c7ecc72d8e48288806ac84

test:
  secret_key_base: 1b9cdd46ada0b8ec5c2a90bb27676c80bb53bc416a2ede58d7af045762b559545644ad11634a81a87fb868d036ea420e48b294bd91a2e791a97344cdf3bb4a01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
